spring:
  datasource:
    url: jdbc:mysql://localhost/bookserver
    username: bookserver
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        hbm2ddl:
          auto: validate
  flyway:
    enabled: true
